#!/usr/bin/env bash
# Makes sure the pre-commit git hook is installed in the current repository.
#
# Git does not version .git/hooks, so a fresh clone (or a deleted hook) has no
# checks at all and `git commit` silently skips them. This is idempotent and
# quiet when the hook is already there; it is run by setup-git-hooks.sh when the
# dev container starts, and by the git shim (git-shim.sh) before every
# `git commit`, so a missing hook is put back before the commit it would guard.
#
# It never blocks a commit: on any problem it says so on stderr and exits 0.
set -uo pipefail

GIT="${REAL_GIT:-git}"
QUIET=0
[ "${1:-}" = "--quiet" ] && QUIET=1

say() { [ "$QUIET" = 1 ] || echo "git hooks: $*" >&2; }

root="$("$GIT" rev-parse --show-toplevel 2>/dev/null)" || exit 0
cd "$root" || exit 0
[ -f .pre-commit-config.yaml ] || exit 0

if "$GIT" config --get core.hooksPath >/dev/null 2>&1; then
  # pre-commit refuses to install while core.hooksPath is set; respect that choice.
  say "core.hooksPath is set, leaving hooks alone"
  exit 0
fi

hook="$("$GIT" rev-parse --git-path hooks/pre-commit)"
if [ -f "$hook" ] && grep -q "File generated by pre-commit" "$hook"; then
  exit 0
fi

if command -v pre-commit >/dev/null 2>&1; then
  precommit=(pre-commit)
elif command -v uv >/dev/null 2>&1; then
  precommit=(uv run pre-commit)
else
  say "pre-commit is not installed; run: uv sync --group dev"
  exit 0
fi

if "${precommit[@]}" install >/dev/null 2>&1; then
  say "pre-commit hook was missing; installed it"
else
  say "could not install the pre-commit hook; run: uv run pre-commit install"
fi
exit 0
