// Design tokens for the web form, consumed by src/input.css through @config.
module.exports = {
  theme: {
    extend: {
      colors: {
        "inverse-primary": "#006c49",
        "text-on-surface": "#dae2fd",
        error: "#ffb4ab",
        "on-secondary-container": "#00452e",
        "on-primary-fixed-variant": "#005236",
        "secondary-fixed-dim": "#45dfa4",
        "glass-border": "rgba(218, 226, 253, 0.1)",
        "on-tertiary-fixed-variant": "#39485a",
        tertiary: "#b9c8de",
        surface: "#0b1326",
        "surface-container-highest": "#2d3449",
        "on-error-container": "#ffdad6",
        "teal-primary": "#10b981",
        "on-surface-variant": "#bbcabf",
        "surface-variant": "#2d3449",
        "on-tertiary-fixed": "#0d1c2d",
        "primary-container": "#10b981",
        "surface-container": "#171f33",
        "on-primary": "#003824",
        outline: "#86948a",
        "surface-container-high": "#222a3d",
        "on-secondary": "#003825",
        "tertiary-fixed-dim": "#b9c8de",
        "surface-dim": "#0b1326",
        "surface-bright": "#31394d",
        "primary-fixed": "#6ffbbe",
        "inverse-on-surface": "#283044",
        "on-tertiary-container": "#2c3a4c",
        "surface-container-lowest": "#060e20",
        "on-secondary-fixed-variant": "#005137",
        "obsidian-base": "#0b1326",
        background: "#0b1326",
        "on-tertiary": "#233143",
        "outline-variant": "#3c4a42",
        "on-surface": "#dae2fd",
        "tertiary-container": "#95a4b9",
        "on-primary-container": "#00422b",
        "inverse-surface": "#dae2fd",
        "error-container": "#93000a",
        "surface-tint": "#4edea3",
        "on-secondary-fixed": "#002114",
        "secondary-container": "#00bd85",
        "primary-fixed-dim": "#4edea3",
        "surface-container-low": "#131b2e",
        "on-error": "#690005",
        "on-background": "#dae2fd",
        "secondary-fixed": "#68fcbf",
        "tertiary-fixed": "#d4e4fa",
        secondary: "#45dfa4",
        primary: "#4edea3",
        "on-primary-fixed": "#002113",
        "emerald-accent": "#10b981",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "margin-desktop": "64px",
        unit: "4px",
        "pane-preview": "55%",
        "gutter-md": "24px",
        "pane-editor": "45%",
        "margin-mobile": "16px",
        gutter: "24px",
        "editor-width": "45%",
        "preview-width": "55%",
      },
      fontFamily: {
        "headline-md-mobile": ["Geist"],
        "display-lg": ["Geist"],
        "code-sm": ["JetBrains Mono"],
        "headline-md": ["Geist"],
        "label-xs": ["JetBrains Mono"],
        "body-lg": ["Geist"],
        "body-md": ["Geist"],
      },
      fontSize: {
        "headline-md-mobile": [
          "24px",
          { lineHeight: "32px", fontWeight: "600" },
        ],
        "display-lg": [
          "48px",
          { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "code-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-md": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "label-xs": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" },
        ],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
      },
    },
  },
};
